### ISSUE TITLE
Using mpg321 a uncaught exception occurd

### ISSUE THREAD

**Issue by pimagical** [thexperiments/pimatic-play#5]
error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'cyan' of undefined at ChildProcess.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-play/node_modules/play/lib/play.js:140:124) at ChildProcess.EventEmitter.emit (events.js:98:17) at Process.ChildProcess._handle.onexit (child_process.js:789:12) This is most probably a bug in pimatic or in a module, please report it!

**Comment by Bhoutman** [comment]
Maybe you didn't install the dependencies yet. I believe this error dissappeared once I did that!
-Hope this issue isn't relevant anymore by now offcourse!
